# Generated by Django 3.1.1 on 2020-11-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201125_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=1000, verbose_name='')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('email', models.CharField(max_length=200, verbose_name='')),
                ('address', models.CharField(max_length=1000, verbose_name='')),
                ('city', models.CharField(max_length=200, verbose_name='')),
                ('state', models.CharField(max_length=200, verbose_name='')),
                ('zip', models.CharField(max_length=200, verbose_name='')),
            ],
        ),
    ]
